language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
services: rabbitmq
before_install:
  - cpanm -n Devel::Cover::Report::Coveralls CPAN::Meta
before_script:
  - mv xt/* t/ #author tests, probably a better way of doing this
  - mv t/100_transaction_memory_leak.t xt/100_transaction_memory_leak.t #doesn't want to run in Devel::Cover
  - perl Makefile.PL
  - cpanm -n --installdeps .
  - make manifest
  - make distdir
  - cd $(perl -MCPAN::Meta -e '$m = CPAN::Meta->load_file("MYMETA.yml"); print $m->name . "-" . $m->version')
  - perl Makefile.PL
script:
  - MQHOST=localhost cover -test -report coveralls -ignore_re "\.c|\.h"
  - MQHOST=localhost perl -I blib/lib -I blib/arch xt/100_transaction_memory_leak.t
