language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
services: rabbitmq
script:
  - perl Makefile.PL
  - make metafile
  - make manifest
  - make dist
  - MQHOST=localhost cpanm --verbose --test-only Net-AMQP-RabbitMQ-*.tar.gz
