language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
services: rabbitmq
script:
  - perl Makefile.PL
  - make manifest
  - make metafile
  - make dist
  - cpanm --look Net-AMQP-RabbitMQ-*.tar.gz
#we do it twice, may as well check that the dist will be correct
  - perl Makefile.PL
  - make
  - prove -v -I blib/lib -I blib/arch t
  - MQHOST=localhost prove -v -I blib/lib -I blib/arch xt
