language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
before_install:
  - sudo apt-get update

install:
  - sudo apt-get -y install rabbitmq-server
  - sudo invoke-rc.d rabbitmq-server start

script:
  - perl Makefile.PL
  - make metafile
  - make manifest
  - make dist
  - MQHSOT=localhost cpanm --verbose --test-only Net-AMQP-RabbitMQ-*.tar.gz
