language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
services: rabbitmq
before_install:
  cpanm -n Devel::Cover::Report::Coveralls
script:
  - perl Makefile.PL
  - make manifest
  - make metafile
  - make dist
  - mkdir _clean
  - mv Net-AMQP-RabbitMQ-*.tar.gz _clean/
  - cd _clean
  - tar -xzf Net-AMQP-RabbitMQ-*.tar.gz
  - cd Net-AMQP-RabbitMQ-*
#we do it twice, may as well check that the dist will be correct
  - perl Makefile.PL
  - cover -test
  - MQHOST=localhost prove -MDevel::Cover -I blib/lib -I blib/arch xt
  - cover -report coveralls -ignore_re "\.c|\.h" cover_db
